#!/bin/ksh
#
############################################
# Script for running spherical shell
# tomography program
############################################
#
path=/exports/work/geos_eip_interfer_backedup/erica/rjmcmc_erica_distr/RJ_MCMC_TOMO/bin
#
########################################################
# Program and files for solving the forward problem with
# the Fast Marching Method
########################################################
#
# Name of program for calculating FMM traveltimes
fmm=$path/fm2dss
# Name of file containing FMM traveltimes
ttim=$path/rtravel.out
# Name of file containing initial traveltimes
ittim=$path/itimes.dat
#
#########################################################
# Program and files for solving the inverse problem using
# subspace inversion
#########################################################
#
# Name of program for performing inversion
inv=$path/subinvss
# Name of file containing iteration number
itn=$path/subiter.in
# Name of file containing initial grid
ing=$path/gridi.vtx
# Name of file containing current grid
cug=$path/gridc.vtx
#
#########################################################
# Program and files for calculating traveltime
# residuals
#########################################################
#
# Name of program for calculating traveltime residuals
resid=$path/residualss
# Name of output file for calculating traveltime residuals
resout=$path/residuals.dat
#
###############################
###############################
cd=chdir
rm=/usr/bin/rm
cp=/usr/bin/cp
typeset -i COUNT
ifile=$path/ttomoss.in
typeset -i NI
typeset -i ITER
###############################
###############################
#
# Open input file and read in variables
#
exec 3<$ifile
  read -u3 NI
exec 3<&-
#
# Start by constructing the velocity grid
#
cp $ing $cug
rm $itn
COUNT=1
exec 4>$itn
   print -u4 $COUNT
exec 4<&-
#
# Now run FMM once to generate reference traveltimes
# and the Frechet matrix.
#
$fmm
#
# Copy initial traveltimes to itimes file
#
cp $ttim $ittim 
#
# Calculate initial residual
#
rm $resout
exec 5>$resout
$resid | (read ttres; print -u5 $ttres)
#
# Now begin a loop to iteratively apply subspace inversion
# and FMM
#
ITER=1
while [[ $ITER -le $NI ]]
do
   $inv
   $fmm
#
#  Calculate traveltime residual
#
   $resd
   $resid | (read ttres; print -u5 $ttres)
   ITER=ITER+1
   rm $itn
   COUNT=ITER
   exec 4>$itn
      print -u4 $COUNT
   exec 4<&-
done
exec 5<&-
